### PR TITLE
AWS Nodejs 10 runtime compatibility.

### PR DESCRIPTION
**Pull request by devasur**
https://github.com/RafalWilinski/serverless-puppeteer-layers/issues/15

You may test with this service endpoint I am leaving around for a few days.  I have confirmed it works with Node 10 runtime.

https://j6m6gtgiyc.execute-api.us-east-1.amazonaws.com/dev/screenshot?address=https://github.com

image

### CODE REVIEW

**Comment by yashutanna** [comment]
+1

this worked perfectly for me. thanks @devasur

**Comment by Meekohi** [comment]
I had to add the full `puppeteer` to `package.json` for local testing to still work. Also had to do:

`executablePath: (process.platform == 'darwin') ? null : await chromium.executablePath,`

**Comment by Meekohi** [comment]
Also @RafalWilinski you should merge this in ASAP -- serverless has deprecated the node8 environment you can't deploy to it anymore.

**Comment by ngduc** [comment]
@RafalWilinski +1 please merge this. This works!

**Pull request merged**
